src/tools/build.jl
ZSH has an environment variable that can change the location of the `.zshrc`file. Updated the config_file definition to respect this variable.
=> Fix zsh config location to respect ZSH environment variables

src/tools/tools.jl
When using the prompts, the behavior is not correct. If it prompts me to update `PATH`, I have to type `n` and then a carriage return to trigger the `read` to finish. It then reads a character, `n` and on the second prompt asking to update `FPATH`, the read already has another character to read which is the `\n` to finish the previous read. This means to deny the second prompt you must preemptively type `nn\n` on the first question. This changes the tty mode so that it reads the raw character input, prompts, reads a single character, and puts the tty mode back. This fixes this bug and also makes it so you don't have to press return on prompts.
=> Fix prompt character input

src/tools/build.jl, test/build.jl, test/parse.jl
This should resolve #48 , the reason why we are not forcing file name to be the one written in config is simply because we might need to provide the flexibility to create alias when there are name conflicts in CLIs, e.g developer could potentially provide alternative file name to install a given command, which is like
file `foo-dark` executes the `foo` command
file `foo` executes another `foo` command
this should make sense. So now we will let people to make sure their file name is the same as entry command name at interface level. The implementation of this part is likely to change due to this feature.
cc: hope this work for you @mehalter
=> Check if entry name is the same as CLI config name

src/tools/build.jl
messages about what is going to be added to config files should be exactly what is going to be inserted. For cases where people's `.julia` folder isn't in their home directory, this message can be incorrect.
=> fix path detection message when .julia folder isn't in ~

src/cast.jl, test/projects/FakePkg/src/FakePkg.jl, test/projects/FakePkg/test/runtests.jl
Hopefully this works for you, it seems like it just needs to return an empty vector of expected type and a nothing. Testing this local resolved the issue for me?
=> resolves #135, zero-length args input to cast_args

src/markdown.jl
This was causing Markdown doc strings to be improperly formatted in help output
=> Fix typo in md_to_string()

src/ast/printing.jl, src/codegen/julia.jl, src/frontend/cast.jl
- fix long signature printing, now produce a more readable error
- fix problem that `-V, --version` is missing in the entry doc
=> fix long sig printing

src/Comonicon.jl, src/argtypes.jl, src/ast/ast.jl, test/argtype.jl, test/runtests.jl
some special types that annotates what kind of string-like input one is expecting, this is really the ideal solution to this since the best way is still to actually have different actual types for path, filename, etc. which is currently missing in Julia, but...
=> add argtypes for better autocompletion

src/ast/printing.jl, src/frontend/cast.jl, test/long_print.jl, test/runtests.jl
originally raised by @GiggleLiu that default hint will error when the default value is too long. Now we limit the default hint generation to 10 chars by default and raise an error points to how to override the default hint in docstring.
=> smarter hint generation for long default value

src/codegen/julia.jl
It is generally expected that command output terminates with a newline.
Without the newline, many shells show an `%`, like so:
and I don't think that's desirable.
=> End version output with newline

src/codegen/julia.jl, test/codegen/codegen.jl, test/codegen/julia/print.jl
=> fix hygenie print

src/codegen/julia.jl, test/builder/install.jl, test/codegen/julia/options.jl
=> fix short option parsing

.gitignore, src/codegen/julia.jl, test/Project.toml, test/builder/install.jl, test/codegen/codegen.jl, test/codegen/julia/config.jl, test/codegen/julia/dash.jl, test/codegen/julia/options.jl
This implements the following dot syntax for long options when the corresponding type
is an option type defined by Configurations, e.g
```julia
using Test
using Comonicon
using Configurations
@option struct OptionA
a::Int
b::Int
end
@option struct OptionB
option::OptionA
c::Int
end
"""
- `-c, --config <path/to/option/or/specific field>`: config.
"""
@main function run(;config::OptionB)
@test config == OptionB(OptionA(1, 1), 1)
end
```
can be used with the following syntax
```sh
command --config.c=1 --config.option.a=1 --config.option.b=1
command --config=config.toml
command -c config.toml
```
=> support option type

src/codegen/julia.jl, test/codegen/julia/config.jl
This should fix combining `--config=<path>` with `--config.<property>=<value>`,
the shell auto-completion still won't work with the `dot` operator syntax tho
cc: @avik-pal
=> fix setting config from cli

src/configs.jl
=> use JULIA_DEPOT_PATH as default install path

src/builder/cli.jl
When I didn' t know how to enable app building, I encountered the confusing `app` command not found error when the help message prints `app` as availalble.
=> add more hint on unknown command

src/builder/install.jl
The current batch script provided by #241 unconditionally returns 0 because there is an `endlocal` line at the end. This patch fixes it by checking julia exit code and handles it.
=> bugfix(windows): handle cmd call error

src/ast/printing.jl
brief has been appended to the end of intro by mistake
this pr fixes this
bug screenshot (see the selected part):
=> fix: brief appended to intro by mistake

src/frontend/cast.jl, test/frontend/cast.jl
user hint is used even when it is empty.
falling back to the default hint now with this PR
=> fix: empty user defined hint is used

example/FakePkg/Project.toml, src/builder/sysimg.jl
Hi, thanks for sharing the package!
Julia 1.9 introduces [package extension](https://pkgdocs.julialang.org/v1/creating-packages/#Conditional-loading-of-code-in-packages-(Extensions)), it seems Comonicon does not support this yet?
I just tried to come up with a quick hack, and it seems working fine in my case. Would be great if someone could have a look at this PR (maybe use this as a hint), and properly support this Julia feature in Comonicon. Thanks!
=> Support weakdeps
