src/tools/build.jl

do not use start up file in CLI.

no start up file

---

.gitignore
README.md
src/tools/build.jl
test/Foo/Comonicon.toml
test/build.jl
test/parse.jl

remove auto-generated precompile execution file, use developer defined ones. resolve #76

Precompile

---

src/builder/cli.jl
test/builder/cli.jl

fix app builder

---

src/builder/install.jl
test/builder/install.jl

use bash instead of sh

---

src/builder/sysimg.jl

fix build on 1.7.1

---

src/ast/types.jl
src/ast/utils.jl
src/frontend/cast.jl
src/frontend/markdown.jl
src/frontend/types.jl
test/ast/ast.jl
test/codegen/julia/arg.jl
test/frontend/markdown.jl

support intro section

---

.ci/test.jl
src/codegen/julia.jl
src/compat.jl
src/frontend/markdown.jl

fix 1.6 support

---

src/ast/printing.jl
src/ast/utils.jl
test/ast/utils.jl
test/runtests.jl

polish printing

---

src/builder/install.jl
src/configs.jl
test/Comonicon.toml
test/options.jl

support nthreads=auto

---

src/ast/types.jl
src/codegen/julia.jl
src/frontend/cast.jl
src/frontend/types.jl
test/codegen/julia/options.jl
test/frontend/cast.jl

add require field for option

---

src/frontend/cast.jl
src/frontend/markdown.jl
test/frontend/markdown.jl

fix emptry docstring

---

src/codegen/julia.jl
test/codegen/julia/config.jl

PR fixes https://github.com/comonicon/Comonicon.jl/issues/228 and adds tests that fail on the current version, but work fine with the fix.

Fixed a bug with optional Config parameters

---

src/frontend/cast.jl

Fix broken links to doc

---

src/ast/printing.jl

A minor fix to an obvious problem.

Show [options] when options are present.

---

test/ast/ast.jl

to make the build badge green again ...

test: update test for #244

---

test/frontend/cast.jl

addressing #254
i left comments in the code diff

test: fix tests for #251

---

docs/src/project.md

as described here: https://github.com/comonicon/Comonicon.jl/pull/268#discussion_r1589418623

Update project.md to remove broken instructions surrounding ion

---

src/configs.jl

explicit hint to julia help section for configs.jl

---

docs/src/project.md

fixing a broken URL in the docs

Update Url to PackageCompiler docs

---

.github/dependabot.yml
.github/workflows/CI.yml
.github/workflows/Documentation.yml
.github/workflows/format-pr.yml
docs/Project.toml
docs/make.jl
docs/src/build.md
docs/src/conventions.md
docs/src/index.md
src/ast/printing.jl
src/configs.jl

- Fix linking in docs
- Use newer Documenter
- Use julia-docdeploy action

Documenter and workflow updates
